version: 0.2
phases:
  install:
    commands:
      - echo install step...
  pre_build:
    commands:
      - aws --version
      - echo logging in to AWS ECR...
      - $(aws ecr get-login --no-include-email --region us-west-2)
  build:
    commands:
      - echo build Docker image on `date`
      - docker build -t sample-express-app:latest .
      - docker tag sample-express-app:latest 904147861902.dkr.ecr.us-west-2.amazonaws.com/manik:latest
  post_build:
    commands:
      - echo build Docker image complete `date`
      - echo push latest Docker images to ECR...
      - docker push 904147861902.dkr.ecr.us-west-2.amazonaws.com/sample-express-app:latest
